add solution for day4
Golang-Insiders/advent-of-code-2023 pull request #12
Opened 2023-12-04 07:02 UTC by ShraddhaAg

This PR adds solution to AoC 2023 day 4.

To run the solution, navigate to the `day4` directory, and run

```
go run main.go <PATH_TO_YOUR_INPUT_FILE>
```

Today was fairly easy as compared to previous days!

2023-12-04 08:30 UTC, teivah commented on day4/main.go
> +	if char >= 48 && char <= 57 {
```suggestion
	if char >= '0' && char <= '9' {
```

2023-12-04 08:31 UTC, teivah commented on day4/main.go
> +	if char >= 48 && char <= 57 {
Just a minor readability comment

2023-12-04 19:27 UTC, alexjoedt requested changes
```go
func findNumberOfCards(input []string) int {
	index := 0
	for {
		if index >= len(input) {
			break
		}

		parts := strings.Fields(input[index])
		cardId, err := strconv.Atoi(strings.TrimSuffix(parts[1], ":"))
		if err != nil {
			panic(err)
		}
		matches := findNumberOfWinNumbers(input[index])
		for i := cardId; i < (cardId + matches); i++ {
			input = append(input, input[i])
		}

		index++
	}

	return index
}
```

2023-12-04 19:27 UTC, alexjoedt commented on day4/main.go
> +func findNumbers(input string) int {
you could return here the result and the matches to use this in findNumberOfCards
`func findNumbers(input string) (int, int)`

2023-12-05 03:32 UTC, ShraddhaAg commented on day4/main.go
> +	if char >= 48 && char <= 57 {
Replaced this with `unicode.IsDigit`.

2023-12-05 07:34 UTC, merged

2023-12-05 10:20 UTC, teivah commented on day4/main.go
> +	if char >= 48 && char <= 57 {
Even better :)